# Stitching Tutorial

The Workflow of the Stitching Pipeline can be seen in the following. Note that the image comes from the [OpenCV Documentation](https://docs.opencv.org/3.4/d1/d46/group__stitching.html).

With the following block, we allow displaying resulting images within the notebook:

In [1]:
import matplotlib.pyplot as plt
import cv2 as cv
import numpy as np
from pathlib import Path

from stitching.image_handler import ImageHandler
from stitching.feature_detector import FeatureDetector
from stitching.feature_matcher import FeatureMatcher
from stitching.camera_estimator import CameraEstimator
from stitching.camera_adjuster import CameraAdjuster
from stitching.camera_wave_corrector import WaveCorrector
from stitching.warper import Warper
from stitching.timelapser import Timelapser

In [2]:
def get_image_paths(img_set):
    return sorted([str(path.relative_to('.')) for path in Path('../../data/sequential_training').rglob(img_set)])

In [6]:
def get_displacement(img_paths):
    img_handler = ImageHandler()
    img_handler.set_img_names(img_paths)

    medium_imgs = list(img_handler.resize_to_medium_resolution())
    final_imgs = list(img_handler.resize_to_final_resolution())

    # final_size = img_handler.get_image_size(final_imgs[0])

    finder = FeatureDetector()
    features = [finder.detect_features(img) for img in medium_imgs]

    matcher = FeatureMatcher()
    matches = matcher.match_features(features)

    camera_estimator = CameraEstimator()
    camera_adjuster = CameraAdjuster()
    wave_corrector = WaveCorrector()

    cameras = camera_estimator.estimate(features, matches)
    cameras = camera_adjuster.adjust(features, matches, cameras)
    cameras = wave_corrector.correct(cameras)

    warper = Warper()
    warper.set_scale(cameras)

    final_sizes = img_handler.get_final_img_sizes()
    camera_aspect = img_handler.get_medium_to_final_ratio()    # since cameras were obtained on medium imgs

    warped_final_imgs = list(warper.warp_images(final_imgs, cameras, camera_aspect))
    final_corners, final_sizes = warper.warp_rois(final_sizes, cameras, camera_aspect)

    def get_first_nonzero_pixel(ndarr):
        return np.argwhere(ndarr > 0)[0][:2]

    def get_center(corner, size):
        return (round(corner[0] + size[1] / 2), round(corner[1] + size[0] / 2))

    timelapser = Timelapser('as_is')
    timelapser.initialize(final_corners, final_sizes)
    centers = []
    for img, corner, size in zip(warped_final_imgs, final_corners, final_sizes):
        timelapser.process_frame(img, corner)
        frame = timelapser.get_frame()
        centers.append(get_center(get_first_nonzero_pixel(frame), size))
    
    centers = np.array(centers)
    return centers, np.diff(centers, axis=0)

In [4]:
sequential_imgs = get_image_paths('*.jpg')

In [7]:
for i in range(5):
    print(get_displacement(sequential_imgs[:5]))

(array([[ 114, 4364],
       [ 226, 4366],
       [ 228, 4531],
       [4898, 1248],
       [4898,  628]]), array([[  112,     2],
       [    2,   165],
       [ 4670, -3283],
       [    0,  -620]]))
(array([[2572, 4024],
       [2684, 4022],
       [2682, 4172],
       [ 278,  290],
       [ 278,  581]]), array([[  112,    -2],
       [   -2,   150],
       [-2404, -3882],
       [    0,   291]]))
(array([[ 114,  129],
       [ 226,  130],
       [ 226,  256],
       [3316, 4241],
       [3316, 4648]]), array([[ 112,    1],
       [   0,  126],
       [3090, 3985],
       [   0,  407]]))
(array([[ 485, 6708],
       [ 596, 6710],
       [ 597, 6834],
       [ 228,  548],
       [ 228,  273]]), array([[  111,     2],
       [    1,   124],
       [ -369, -6286],
       [    0,  -275]]))
(array([[ 114,  188],
       [ 226,  192],
       [ 228,  371],
       [4084, 4354],
       [4085, 4670]]), array([[ 112,    4],
       [   2,  179],
       [3856, 3983],
       [   1,  316]]))
